name: Run Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install gdal-bin python3-gdal -y
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy rasterio geopandas shapely matplotlib
      - name: Run unittest
        run: |
          python -m unittest discover -s tests
